version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/swy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: swy
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

brews:
  - repository:
      owner: mynameismaxz
      name: homebrew-tap
      branch: main
    commit_author:
      name: mynameismaxz
      email: mynameismaxz@users.noreply.github.com
    homepage: https://github.com/mynameismaxz/switchy
    description: "CLI tool for managing named env-var profiles and applying them to your shell"
    license: "MIT"
    install: |
      bin.install "swy"
    test: |
      system "#{bin}/swy --version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
